### ISSUE TITLE
Буряк Софтовый Допил

### ISSUE THREAD

**Issue by tank-uk** [andykarpov/buryak-pi-2020#1]
выбор банка ПЗУ по клавишам F1-F8
F1 - PC4-0 , PC5-0 , PD0-0 ; F2 - PC4-1 , PC5-0 , PD0-0 ; F3 - PC4-0 , PC5-1 , PD0-0 ; F4 - PC4-0 , PC5-0 , PD0-1 ; 
F5 - PC4-1 , PC5-0 , PD0-0 ; F6 - PC4-1 , PC5-1 , PD0-0 ; F7 - PC4-1 , PC5-0 , PD0-1 ; F8 - PC4-1 , PC5-1 , PD0-1
F11 - Reset
F12 - NMI
Scroll Lock - Turbo
Pause - WAIT CPU
две прошивки для атмега : 1 - со стандартным мех.джойстиком (Atari) . вторая под джойстик Sega

убрать Z состояние с R0 , G0 . B0 , и наверное с R2 и G2 ( или не устанавливать резисторы R17 и R20)
сделать отключение DivMMC по сигналу "1" на  SD_Detect (128 pin Maxa)
расширить ОЗУ хотя бы до 512к

**Comment by andykarpov** [comment]
банки ПЗУ - ок, сделаем.
ресет и NMI перенесем :)
турбу надо реализовать.
паузу проца - надо подумать, на один такт или вообще до следующего нажатия тормозить?

по поводу сега джоя - нужно с Олегом консультироваться :)
переделать VGA - сделаем.
SD_Detect - отличная идея.
ОЗУ до 512кб - по какому стандарту? 7ffd 7,6 ?

Все эти хотелки желательно в отдельные issues завести.

**Comment by tank-uk** [comment]
Турбо это на будущее
озу наверное по Профику
Вейт в тригерном режиме , до следующего нажатия и с индикацией светодиодом LED_XX на порту РС3 меги

**Comment by andykarpov** [comment]
Я завел отдельные задачи, эту можно закрывать
